[versions]
alchemist = "25.6.0"
kotlin = "1.8.0"
scalapy = "0.5.3"
logback = "1.4.5"

[libraries]
alchemist = { module = "it.unibo.alchemist:alchemist", version.ref = "alchemist" }
alchemist-protelis = { module = "it.unibo.alchemist:alchemist-incarnation-protelis", version.ref = "alchemist" }
alchemist-scafi = { module = "it.unibo.alchemist:alchemist-incarnation-scafi", version.ref = "alchemist" }
scalapy = { module = "dev.scalapy:scalapy-core_2.13", version.ref = "scalapy" }
logbackClassic = { module = "ch.qos.logback:logback-classic", version.ref = "logback" }

[bundles]
alchemist-protelis = [ "alchemist", "alchemist-protelis" ]
alchemist-scafi = [ "alchemist", "alchemist-scafi" ]

[plugins]
gitSemVer = { id = "org.danilopianini.git-sensitive-semantic-versioning", version = "0.3.0" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-qa = { id = "org.danilopianini.gradle-kotlin-qa", version = "0.29.2" }
multiJvmTesting = { id = "org.danilopianini.multi-jvm-test-plugin", version = "0.4.15" }
taskTree = { id = "com.dorongold.task-tree", version = "2.1.0" }
