name: CI
on:
  push:
    tags: '*'
    branches-ignore:
      - 'autodelivery**'
      - 'bump-**'
      - 'renovate/**'
    paths-ignore:
      - 'CHANGELOG.md'
      - 'LICENSE'
      - 'README.md'
      - 'renovate.json'
  pull_request:
  workflow_dispatch:

jobs:
  compute-version:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.version }}
    steps:
      - name: Checkout
        uses: danysk/action-checkout@0.2.5
      - id: version
        run: |
          echo "::set-output name=version::$(./gradlew printGit | grep -oP '^Version computed by GitSemVer: \K.*$')"
  check-simulations:
    strategy:
      matrix:
        os: [ ubuntu ] ## ScalaPy works only on ubuntu
    runs-on: ${{ matrix.os }}-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3.3.0
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Upgrade pip
      run: pip install --upgrade pip --user
    - name: Install requirements
      run: pip install -r requirements.txt --user
    - uses: DanySK/build-check-deploy-gradle-action@2.1.26
      with:
        build-command: true
        check-command: ./gradlew runAllGraphic
        deploy-command: true
        should-run-codecov: false
  ci-success:
    runs-on: ubuntu-latest
    needs: [check-simulations]
    if: always() && !contains(join(needs.*.result, ','), 'cancelled')
    steps:
      - name: All phases successful
        run: ${{ !contains(join(needs.*.result, ','), 'failure') }}
